services:
  - type: web
    name: reviews-copilot-frontend
    env: node
    buildCommand: npm run build
    startCommand: npm run preview
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
    domains:
      - reviews-copilot-frontend.onrender.com
    headers:
      - name: X-Content-Type-Options
        value: nosniff
      - name: X-Frame-Options
        value: DENY
      - name: X-XSS-Protection
        value: 1; mode=block